script:
  - npm test --single-run
  - node_modules/.bin/protractor spec/e2e/prot.conf.js --browser=firefox
  - grunt jasmine
language: node_js
node_js:
  - "0.10"
before_script:
  - bower install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm start > /dev/null &
  - webdriver-manager update
  - sleep 3
  - npm install -g grunt-cli
  - npm install grunt-cli
  - npm install grunt-contrib-jasmine

#whitelist
branches:
  only:
    - master
    - development-branch
